(() => {
  'use strict';
  const $ = (s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
  const esc = v => String(v ?? '').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
  const ago = iso => { const n=Math.max(0,Date.now()-new Date(iso||Date.now()).getTime())/1000; if(n<60)return `${Math.round(n)}s`; if(n<3600)return `${Math.round(n/60)}m`; if(n<86400)return `${Math.round(n/3600)}h`; return `${Math.round(n/86400)}d`; };
  const toast = (m)=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(window.__spikeToast);window.__spikeToast=setTimeout(()=>t.classList.remove('show'),2400)};
  const open = id=>$('#'+id)?.classList.add('show'); const close=id=>$('#'+id)?.classList.remove('show');

  const packs = [
    ['now','🔴 LIVE NOW','All currently live streams'],['momentum','⚡ RISING FAST','Streams with the strongest current momentum'],['trending','🔥 TRENDING','Current attention across Live'],['breakout','🚀 BREAKOUT','High momentum relative to current audience'],['participation','⚡ PARTICIPATION','Streams with active audience interaction'],['conversation','💬 CONVERSATIONS','Streams with sustained chat and retention'],['guest','🎙 NEEDS A GUEST','Live streams currently open to guests'],['collab','🤝 COLLABORATION','Guest-enabled streams with strong discovery signals'],['audience','🗳 AUDIENCE DECIDES','Streams with active polls and audience actions'],['moments','🔥 MOMENT HAPPENING','Streams generating recent Moments'],['community','🏠 RETURNING COMMUNITY','Streams with returning viewers'],['retention','⏱ RETENTION','Streams where viewers are staying'],['fast','📈 FASTEST MOMENTUM','Highest momentum signal'],['starting','⏰ STARTING SOON','Scheduled Live streams']
  ];
  const state={streams:[],profiles:[],mode:'now',query:'',user:null,loaded:false,hostMedia:null,hostChannel:null,hostPeers:new Map(),hostGuestPeers:new Map(),watchPc:null,watchChannel:null,watchStreamId:null,watchMode:'viewer',poll:null,pollChannel:null,eventChannel:null,questionChannel:null,momentChannel:null,presenceChannel:null,presenceTimer:null,questions:[],moments:[],presenceState:{},guestPc:null,guestChannel:null,guestId:null,guestMedia:null,guestInviteChannel:null,chatChannel:null};
  const scores={
    now:s=>s.viewer_count*0.3+s.momentum*0.35+s.quality_score*.2+s.discovery_score*.15,
    momentum:s=>s.momentum*0.7+s.viewer_count*.03+s.spark_count*.02+s.chat_count*.02+s.moment_count*.02,
    trending:s=>s.viewer_count*.18+s.momentum*.28+s.spark_count*.16+s.chat_count*.14+s.share_count*.08+s.retention_percent*.08+s.quality_score*.08,
    breakout:s=>s.momentum*.55+s.discovery_score*.25+s.retention_percent*.12+s.viewer_count*.03+s.spark_count*.05,
    new:s=>s.discovery_score*.45+s.momentum*.35+s.quality_score*.2,
    participation:s=>s.spark_count*.22+s.poll_count*9+s.chat_count*.22+s.moment_count*7+s.guest_count*8+s.momentum*.12,
    conversation:s=>s.chat_count*.28+s.spark_count*.18+s.poll_count*9+s.returning_viewers*.16+s.retention_percent*.18+s.quality_score*.2,
    guest:s=>(s.guest_open?50:0)+(s.guest_slots*12)+s.momentum*.2+s.quality_score*.2+s.discovery_score*.2,
    collab:s=>s.guest_open? s.discovery_score*.45+s.quality_score*.35+s.momentum*.2 : -1,
    expertise:s=>s.quality_score*.55+s.retention_percent*.25+s.discovery_score*.2,
    audience:s=>s.poll_count*12+s.spark_count*.22+s.chat_count*.18+s.moment_count*7+s.momentum*.15,
    moments:s=>s.moment_count*9+s.momentum*.35+s.spark_count*.2+s.chat_count*.15,
    community:s=>s.returning_viewers*.3+s.retention_percent*.25+s.quality_score*.25+s.momentum*.2,
    retention:s=>s.retention_percent*.55+s.avg_watch_seconds*.03+s.returning_viewers*.12+s.quality_score*.3,
    fast:s=>s.momentum*.55+(s.viewer_count/10)*.2+s.spark_count*.1+s.chat_count*.1+s.discovery_score*.05,
    starting:s=>s.discovery_score*.45+s.quality_score*.25+s.momentum*.3,
    daily:s=>s.quality_score*.3+s.momentum*.25+s.viewer_count*.12+s.spark_count*.12+s.retention_percent*.11+s.returning_viewers*.1,
  };
  function rank(list,mode){const fn=scores[mode]||scores.now;return [...list].sort((a,b)=>fn(b)-fn(a));}
  function formatNum(n){n=Number(n)||0;return n>=1000000?(n/1e6).toFixed(1)+'M':n>=1000?(n/1000).toFixed(n>=10000?0:1)+'K':String(Math.round(n));}
  function hostName(s){return s.host||state.profiles.find(p=>p.id===s.host_id)?.display_name||state.profiles.find(p=>p.id===s.host_id)?.username||'SPIKE Creator'}
  function renderTabs(){ $('#liveTabs').innerHTML=packs.map(([id,label])=>`<button class="live-tab ${state.mode===id?'active':''}" data-mode="${id}">${label}</button>`).join(''); }
  function filtered(){const q=state.query.toLowerCase();return state.streams.filter(s=>s.status==='live'||(state.mode==='starting'&&s.status==='scheduled')).filter(s=>!q||`${s.title} ${hostName(s)} ${s.category} ${(s.tags||[]).join(' ')}`.toLowerCase().includes(q));}
  function renderHero(){const s=rank(filtered(),state.mode)[0]||state.streams[0];if(!s){$('#heroSection').innerHTML='<div class="empty-live"><strong>No live broadcasts yet</strong>Start the first SPIKE Live and create the moment.</div>';return}$('#heroSection').innerHTML=`<article class="hero-video">${s.thumbnail_url?`<img src="${esc(s.thumbnail_url)}" alt="">`:'<div class="stream-cover-placeholder" aria-hidden="true"></div>'}<div class="hero-overlay"><span class="live-badge"><i class="pulse-dot"></i> LIVE · ${formatNum(s.viewer_count)} watching</span><div class="hero-title">${esc(s.title)}</div><div class="hero-meta">${esc(hostName(s))} · ${esc(s.category)} · ⚡ ${Math.round(s.momentum||0)} Momentum · ${Math.round(s.retention_percent||0)}% retention</div><div class="hero-actions"><button class="hero-btn primary" data-action="join" data-id="${s.id}">▶ Join Live</button><button class="hero-btn" data-action="spark" data-id="${s.id}">⚡ Spark</button><button class="hero-btn" data-action="guest" data-id="${s.id}">🎙 Bring Guest</button><button class="hero-btn" data-action="moment" data-id="${s.id}">🔥 Mark Moment</button></div></div></article><aside class="live-intel"><div class="intel-card"><h3>⚡ Live Momentum</h3><div class="intel-value">${Math.round(s.momentum||0)}</div><div class="meter"><i style="width:${Math.min(100,Math.max(4,s.momentum||0))}%"></i></div><div class="intel-sub">Growth + participation + freshness. This is not a viewer-count ranking.</div></div><div class="intel-card"><h3>🧠 Why this is here</h3><div class="metric-row"><div class="metric"><strong>${formatNum(s.spark_count)}</strong><span>Sparks</span></div><div class="metric"><strong>${formatNum(s.chat_count)}</strong><span>Chat</span></div><div class="metric"><strong>${Math.round(s.retention_percent)}%</strong><span>Retention</span></div><div class="metric"><strong>${s.moment_count}</strong><span>Moments</span></div></div></div><div class="intel-card"><h3>🎙 Guest-ready</h3><div class="intel-value" style="font-size:21px">${s.guest_open?'Open':'Host only'}</div><div class="intel-sub">${s.guest_open?`${s.guest_slots} guest slot${s.guest_slots===1?'':'s'} available.`:'This host is not currently accepting guests.'}</div></div></aside>`; }
  function card(s,rankNo,mode){return `<article class="stream-card"><div class="stream-cover">${s.thumbnail_url?`<img src="${esc(s.thumbnail_url)}" alt="" loading="lazy">`:'<div class="stream-cover-placeholder" aria-hidden="true"></div>'}<div class="cover-grad"></div><span class="rank-pill">#${rankNo} · ${esc((packs.find(x=>x[0]===mode)||['','LIVE'])[1].replace(/^[^ ]+ /,''))}</span><span class="viewer-pill">🔴 ${formatNum(s.viewer_count)}</span><span class="momentum-pill">⚡ ${Math.round(s.momentum||0)}</span></div><div class="stream-body"><div class="stream-title">${esc(s.title)}</div><div class="stream-host"><img class="host-avatar" src="${esc(s.avatar_url||'')}" alt="" onerror="this.style.display='none'"><div class="host-copy"><strong>${esc(hostName(s))}</strong><span>${esc(s.category)} · ${ago(s.started_at)} ago</span></div></div><div class="stream-stats"><span>💬 ${formatNum(s.chat_count)}</span><span>⚡ ${formatNum(s.spark_count)}</span><span>🔥 ${s.moment_count}</span><span>🎙 ${s.guest_open?'Guest open':'Closed'}</span></div><div class="stream-actions"><button class="stream-action primary" data-action="join" data-id="${s.id}">Join</button><button class="stream-action" data-action="spark" data-id="${s.id}">⚡</button><button class="stream-action" data-action="guest" data-id="${s.id}">🎙</button><button class="stream-action" data-action="save" data-id="${s.id}">☆</button></div></div></article>`}
  function renderMain(){const list=rank(filtered(),state.mode);const title=(packs.find(x=>x[0]===state.mode)||packs[0]);$('#mainSections').innerHTML=`<div class="section-head"><div><h2>${title[1]}</h2><p>${title[2]} · ${list.length} live streams</p></div><button class="section-link" data-mode="now">Reset</button></div><div class="live-grid">${list.slice(0,8).map((s,i)=>card(s,i+1,state.mode)).join('')||'<div class="empty-live"><strong>No matching live streams</strong>Try another ranking pack or search.</div>'}</div>`;}
  function renderRanks(){const modes=['momentum','breakout','participation','conversation','guest','collab','retention','community','fast'];const list=filtered();$('#rankBoard').innerHTML=modes.map(m=>{const rs=rank(list,m).slice(0,3);const p=packs.find(x=>x[0]===m);return `<div class="rank-card"><h3>${p[1]}</h3><div class="rank-list">${rs.map((s,i)=>`<div class="rank-item"><span class="rank-num">${i+1}</span><div><strong>${esc(hostName(s))}</strong><span>${esc(s.title)}</span></div><b class="rank-score">${Math.round((scores[m]||scores.now)(s))}</b></div>`).join('')||'<div class="rank-item"><span>No data</span></div>'}</div></div>`}).join('');}
  function renderLiveActivity(){const list=filtered();const totals=list.reduce((a,s)=>{a.viewers+=Number(s.viewer_count)||0;a.chat+=Number(s.chat_count)||0;a.sparks+=Number(s.spark_count)||0;a.moments+=Number(s.moment_count)||0;return a},{viewers:0,chat:0,sparks:0,moments:0});$('#liveActivityGrid').innerHTML=`<div class="mission"><div class="mission-top"><strong>👀 Live viewers</strong><small>Current streams</small></div><div class="mission-foot"><span>${formatNum(totals.viewers)}</span><b>viewers</b></div></div><div class="mission"><div class="mission-top"><strong>💬 Conversation</strong><small>Recorded chat messages</small></div><div class="mission-foot"><span>${formatNum(totals.chat)}</span><b>messages</b></div></div><div class="mission"><div class="mission-top"><strong>⚡ Sparks</strong><small>Recorded audience signals</small></div><div class="mission-foot"><span>${formatNum(totals.sparks)}</span><b>sparks</b></div></div><div class="mission"><div class="mission-top"><strong>🔥 Moments</strong><small>Captured Live highlights</small></div><div class="mission-foot"><span>${formatNum(totals.moments)}</span><b>moments</b></div></div>`;}
  function renderAll(){renderTabs();renderHero();renderMain();renderRanks();renderLiveActivity();}
  async function getClient(){return window.__SPIKE_SUPABASE__||window.supabaseClient||window.sb||null;}
  async function load(){const sb=await getClient();if(!sb){state.streams=[];state.loaded=true;renderAll();toast('Live is unavailable until the SPIKE connection is ready.');return}try{const {data:{user}}=await sb.auth.getUser();state.user=user||null;const {data:streams,error}=await sb.from('spike_live_streams').select('*').in('status',['live','scheduled']).order('started_at',{ascending:false,nullsFirst:false}).limit(100);if(error)throw error;const ids=(streams||[]).map(x=>x.host_id).filter(Boolean);let profiles=[];if(ids.length){const r=await sb.from('profiles').select('id,display_name,username,avatar_url,verified,level,rank').in('id',ids);profiles=r.data||[]}state.profiles=profiles;state.streams=(streams||[]).map(s=>{const p=profiles.find(x=>x.id===s.host_id)||{};return {...s,host:p.display_name||p.username||'SPIKE Creator',avatar_url:p.avatar_url||''}});state.loaded=true;renderAll();subscribeRealtime(sb);listenGuestInvites();const requestedStream=new URLSearchParams(location.search).get('stream');if(requestedStream){const requested=state.streams.find(x=>String(x.id)===String(requestedStream)&&x.status==='live');if(requested)join(requested.id);else toast('That Live is no longer available.')}}catch(e){console.error('SPIKE Live load failed',e);state.streams=[];state.loaded=true;renderAll();toast('Live could not be loaded. Please try again.');}}
  function subscribeRealtime(sb){try{sb.channel('spike-live-page').on('postgres_changes',{event:'*',schema:'public',table:'spike_live_streams'},()=>load()).subscribe();if(state.user)sb.channel('spike-live-guest-inbox').on('postgres_changes',{event:'INSERT',schema:'public',table:'spike_live_guests',filter:`guest_id=eq.${state.user.id}`},payload=>{if(payload.new?.status==='pending')toast('🎙 You have a new Live guest invitation')}).subscribe()}catch(e){console.warn(e)}}
  async function event(streamId,type,metadata={}){const sb=await getClient();if(!sb||!state.user){toast('Sign in to participate in Live.');return}const {error}=await sb.from('spike_live_events').insert({stream_id:streamId,actor_id:state.user.id,event_type:type,metadata});if(error)toast(error.message);else{const s=state.streams.find(x=>x.id===streamId);if(s){if(type==='spark')s.spark_count++;if(type==='chat')s.chat_count++;if(type==='share')s.share_count++;if(type==='moment')s.moment_count++;if(type==='guest_join')s.guest_count++;renderAll()}toast(type==='spark'?'⚡ Spark sent':type==='moment'?'🔥 Moment marked':'Participation recorded');}}
  async function markMoment(){const streamId=state.watchStreamId;if(!streamId)return;const sb=await getClient();if(!sb||!state.user){toast('Sign in to mark a Moment.');return}const title=(prompt('Name this Moment (optional)')||'').trim().slice(0,120)||null;const video=$('#watchVideo');const playback=Number.isFinite(video?.currentTime)?Math.floor(video.currentTime):null;const {error}=await sb.from('spike_live_moments').insert({stream_id:streamId,creator_id:state.user.id,title,moment_type:'highlight',playback_seconds:playback});if(error){toast(error.message);return}await event(streamId,'moment',{title,playback_seconds:playback});await loadLiveMoments(streamId);toast('🔥 Moment captured')}
  async function loadLiveMoments(streamId){const sb=await getClient();if(!sb||!state.user)return;const {data}=await sb.from('spike_live_moments').select('id,creator_id,title,moment_type,playback_seconds,featured,created_at').eq('stream_id',streamId).order('created_at',{ascending:false}).limit(20);state.moments=data||[];renderMoments()}
  function renderMoments(){const box=$('#momentList');if(!box)return;box.innerHTML=state.moments.map(m=>`<div class="moment-card"><strong>${esc(m.title||'Live highlight')}</strong><small>${esc(m.moment_type)} · ${ago(m.created_at)} ago${m.playback_seconds!=null?` · ${Math.floor(m.playback_seconds/60)}:${String(m.playback_seconds%60).padStart(2,'0')}`:''}</small></div>`).join('')||'<span style="color:var(--live-muted);font-size:9px">No Moments yet.</span>'}
  async function subscribeMoments(sb,streamId){if(!sb)return;if(state.momentChannel)try{sb.removeChannel(state.momentChannel)}catch(_){}const ch=sb.channel(`spike-live-moments:${streamId}`).on('postgres_changes',{event:'*',schema:'public',table:'spike_live_moments',filter:`stream_id=eq.${streamId}`},()=>loadLiveMoments(streamId)).subscribe();state.momentChannel=ch}
  async function loadChat(streamId){const sb=await getClient();if(!sb||!state.user){$('#chatStatus').textContent='Sign in to chat';return}$('#chatStatus').textContent='Loading…';const {data,error}=await sb.from('spike_live_chat_messages').select('id,user_id,message,created_at').eq('stream_id',streamId).order('created_at',{ascending:false}).limit(80);if(error){$('#chatStatus').textContent='Chat unavailable';return}const ids=[...new Set((data||[]).map(x=>x.user_id))];let ps=[];if(ids.length){const r=await sb.from('profiles').select('id,display_name,username').in('id',ids);ps=r.data||[]}renderChat((data||[]).reverse(),ps);if(state.chatChannel)try{await sb.removeChannel(state.chatChannel)}catch(_){}const ch=sb.channel(`spike-live-chat:${streamId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'spike_live_chat_messages',filter:`stream_id=eq.${streamId}`},async payload=>{const row=payload.new;let name='SPIKE';const pr=await sb.from('profiles').select('display_name,username').eq('id',row.user_id).maybeSingle();name=pr.data?.display_name||pr.data?.username||name;appendChat(row,name);}).subscribe(status=>{$('#chatStatus').textContent=status==='SUBSCRIBED'?'Live':'Connecting…'});state.chatChannel=ch} 
function renderChat(rows,profiles){const box=$('#chatMessages');if(!box)return;box.innerHTML=rows.map(r=>{const p=profiles.find(x=>x.id===r.user_id);return chatHtml(r,p?.display_name||p?.username||'SPIKE')}).join('')||'<div style="color:var(--live-muted);font-size:10px;text-align:center;padding:20px">Be the first to say something.</div>';box.scrollTop=box.scrollHeight}
function chatHtml(r,name){return `<div class="chat-message"><strong>${esc(name)}</strong>${esc(r.message)}<time>${ago(r.created_at)}</time></div>`}
function appendChat(r,name){const box=$('#chatMessages');if(!box)return;const empty=box.querySelector('[style*="text-align:center"]');if(empty)empty.remove();box.insertAdjacentHTML('beforeend',chatHtml(r,name));box.scrollTop=box.scrollHeight}
async function sendChat(){const input=$('#chatInput');const message=String(input?.value||'').trim();if(!message)return;const sb=await getClient();if(!sb||!state.user||!state.watchStreamId){toast('Sign in to chat.');return}const {data:mod}=await sb.from('spike_live_moderation_actions').select('action').eq('stream_id',state.watchStreamId).eq('target_user_id',state.user.id).in('action',['mute','block','remove']).limit(1);if(mod?.length){toast('You cannot participate in this Live chat right now.');return}const {error}=await sb.from('spike_live_chat_messages').insert({stream_id:state.watchStreamId,user_id:state.user.id,message});if(error)toast(error.message);else{input.value='';await event(state.watchStreamId,'chat');}}
async function openGuestInbox(){const sb=await getClient();if(!sb||!state.user){location.href='index.html?auth=signin&next='+encodeURIComponent(location.pathname+location.search);return}const {data,error}=await sb.from('spike_live_guests').select('id,stream_id,guest_id,status,note,created_at').eq('host_id',state.user.id).eq('status','pending').order('created_at',{ascending:false}).limit(30);if(error){toast(error.message);return}const ids=[...new Set((data||[]).map(x=>x.guest_id))];let ps=[];if(ids.length){const r=await sb.from('profiles').select('id,display_name,username,level,rank').in('id',ids);ps=r.data||[]}$('#guestInboxList').innerHTML=(data||[]).map(g=>{const p=ps.find(x=>x.id===g.guest_id)||{};return `<div class="guest-request"><strong>${esc(p.display_name||p.username||'Creator')}</strong><small>${esc(p.rank||'Creator')} · Level ${p.level||1} · ${ago(g.created_at)}</small><div class="guest-request-actions"><button class="stream-action" data-guest-decision="declined" data-guest-id="${g.id}">Decline</button><button class="stream-action primary" data-guest-decision="accepted" data-guest-id="${g.id}">Accept</button></div></div>`}).join('')||'<div style="color:var(--live-muted);font-size:11px">No pending guest requests.</div>';open('guestInboxSheet')}
async function decideGuest(id,status){const sb=await getClient();if(!sb||!state.user)return;const {data,error}=await sb.from('spike_live_guests').update({status,responded_at:new Date().toISOString()}).eq('id',id).eq('host_id',state.user.id).select('stream_id,guest_id').maybeSingle();if(error){toast(error.message);return}toast(status==='accepted'?'🎙 Guest accepted':'Guest request declined');await openGuestInbox();if(data?.stream_id)await event(data.stream_id,status==='accepted'?'guest_join':'guest_request',{guest_id:data.guest_id,status});}
  function rtcConfig(){return {iceServers:[{urls:'stun:stun.l.google.com:19302'},{urls:'stun:stun1.l.google.com:19302'}]}}
  function guestTile(id,name,stream){const wrap=$('#guestStage');if(!wrap)return;wrap.hidden=false;let tile=document.getElementById(`guest-tile-${id}`);if(!tile){tile=document.createElement('div');tile.className='guest-tile';tile.id=`guest-tile-${id}`;tile.innerHTML=`<video autoplay playsinline></video><span class="guest-label">${esc(name||'Guest')}</span>`;wrap.appendChild(tile)}tile.querySelector('video').srcObject=stream}
  function removeGuestTile(id){document.getElementById(`guest-tile-${id}`)?.remove();if(!$('#guestStage')?.children.length)$('#guestStage').hidden=true}
  async function join(id){const s=state.streams.find(x=>x.id===id);if(!s)return;await event(id,'join');state.watchStreamId=id;state.watchMode=state.user?.id===s.host_id?'host':'viewer';open('watchSheet');await loadChat(id);await loadLivePoll(id);await loadLiveQuestions(id);await loadLiveMoments(id);await subscribeQuestions(await getClient(),id);await subscribeLiveEvents(await getClient(),id);await subscribeMoments(await getClient(),id);await subscribePresence(await getClient(),id);$('#watchTitle').textContent=`🔴 ${hostName(s)} · Live`;$('#watchMeta').textContent=`${s.title} · ${s.category} · ${formatNum(s.viewer_count)} watching`;$('#watchState').textContent='Connecting to Live…';$('#guestInviteBar').hidden=true;$('#guestStage').hidden=true;$('#hostAudienceControls').hidden=state.watchMode!=='host';$('#liveControlRoom').hidden=state.watchMode!=='host';if(state.watchMode==='host'&&state.hostMedia){$('#watchVideo').srcObject=state.hostMedia;$('#watchState').textContent='You are live · host camera';return}if(s.playback_url){$('#watchVideo').src=s.playback_url;$('#watchVideo').play().catch(()=>{});$('#watchState').textContent='';return}const sb=await getClient();if(!sb||!window.RTCPeerConnection){$('#watchState').textContent='Live video transport is unavailable in this browser.';return}const topic=`spike-live:${id}`,ch=sb.channel(topic),peerId=crypto.randomUUID?.()||String(Date.now());state.watchChannel=ch;state.watchPc=new RTCPeerConnection(rtcConfig());state.watchPc.ontrack=e=>{if(e.streams?.[0]){$('#watchVideo').srcObject=e.streams[0];$('#watchState').textContent='';}};state.watchPc.onicecandidate=e=>{if(e.candidate)ch.send({type:'broadcast',event:'ice',payload:{role:'viewer',peerId,candidate:e.candidate,target:'host'}})};ch.on('broadcast',{event:'offer'},async({payload})=>{if(payload?.role!=='host'||payload.target!==peerId)return;try{await state.watchPc.setRemoteDescription(payload.sdp);const ans=await state.watchPc.createAnswer();await state.watchPc.setLocalDescription(ans);await ch.send({type:'broadcast',event:'answer',payload:{role:'viewer',peerId,sdp:ans,target:payload.peerId}})}catch(e){console.warn(e)}}).on('broadcast',{event:'ice'},async({payload})=>{if(payload?.role!=='host'||payload.target!==peerId||!payload.candidate)return;try{await state.watchPc.addIceCandidate(payload.candidate)}catch(_){}}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.send({type:'broadcast',event:'viewer-join',payload:{role:'viewer',peerId}})})}

  async function setupGuestTransport(streamId,guestId){const sb=await getClient();if(!sb||!state.user)return;const s=state.streams.find(x=>x.id===streamId);if(!s)return;try{state.guestMedia=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:true})}catch(_){toast('Camera and microphone permission is required to join as a guest.');return}state.guestId=guestId;state.guestStream=streamId;state.watchStreamId=streamId;state.watchMode='guest';open('watchSheet');$('#watchTitle').textContent=`🎙 Guest · ${hostName(s)} · Live`;$('#watchVideo').srcObject=state.guestMedia;$('#watchState').textContent='Guest camera + microphone';const topic=`spike-live:${streamId}`,ch=sb.channel(topic),peerId=crypto.randomUUID?.()||String(Date.now());state.guestChannel=ch;state.guestPc=new RTCPeerConnection(rtcConfig());state.guestMedia.getTracks().forEach(t=>state.guestPc.addTrack(t,state.guestMedia));state.guestPc.onicecandidate=e=>{if(e.candidate)ch.send({type:'broadcast',event:'guest-ice',payload:{role:'guest',peerId,guestId,candidate:e.candidate,target:'host'}})};ch.on('broadcast',{event:'guest-offer'},async({payload})=>{if(payload?.target!==peerId)return;try{await state.guestPc.setRemoteDescription(payload.sdp);const ans=await state.guestPc.createAnswer();await state.guestPc.setLocalDescription(ans);await ch.send({type:'broadcast',event:'guest-answer',payload:{role:'guest',peerId,guestId,sdp:ans,target:payload.peerId}})}catch(_){toast('Guest connection failed')}}).on('broadcast',{event:'guest-ice'},async({payload})=>{if(payload?.role!=='host'||payload.target!==peerId||!payload.candidate)return;try{await state.guestPc.addIceCandidate(payload.candidate)}catch(_){}}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.send({type:'broadcast',event:'guest-join',payload:{role:'guest',peerId,guestId,name:state.user.user_metadata?.display_name||'Guest'}})});toast('🎙 Joining as guest…')}

  async function listenGuestInvites(){const sb=await getClient();if(!sb||!state.user)return;const ch=sb.channel(`spike-live-guest-invites:${state.user.id}`).on('postgres_changes',{event:'UPDATE',schema:'public',table:'spike_live_guests',filter:`guest_id=eq.${state.user.id}`},payload=>{if(payload.new?.status!=='accepted')return;const streamId=payload.new.stream_id;$('#guestInviteBar').hidden=false;$('#guestInviteBar').innerHTML=`<span>🎙 You were accepted as a guest.</span><button id="joinGuestNow">Join</button>`;$('#joinGuestNow').onclick=()=>setupGuestTransport(streamId,payload.new.id);toast('🎙 Your guest request was accepted')}).subscribe();state.guestInviteChannel=ch}

  async function guests(id){const s=state.streams.find(x=>x.id===id);if(!s)return;if(!s.guest_open){toast('This host is not accepting guests right now.');return}$('#guestSub').textContent=`Invite someone into “${s.title}”.`;$('#guestList').innerHTML='<div style="color:var(--live-muted);font-size:11px">Loading people you can invite…</div>';open('guestSheet');const sb=await getClient();if(!sb||!state.user){$('#guestList').innerHTML='<div style="color:var(--live-muted);font-size:11px">Sign in to send guest requests.</div>';return}const {data,error}=await sb.from('profiles').select('id,display_name,username,avatar_url,verified,level,rank').neq('id',state.user.id).order('level',{ascending:false}).limit(12);if(error){$('#guestList').innerHTML=`<div style="color:var(--live-muted);font-size:11px">${esc(error.message)}</div>`;return}$('#guestList').innerHTML=(data||[]).map(p=>`<div style="display:flex;align-items:center;gap:10px;padding:10px;border:1px solid var(--live-line);border-radius:14px"><div style="flex:1"><strong style="font-size:11px">${esc(p.display_name||p.username||'Creator')}</strong><span style="display:block;color:var(--live-muted);font-size:9px">${esc(p.rank||'Creator')} · Level ${p.level||1}</span></div><button class="live-primary" style="padding:8px 10px;font-size:9px" data-invite="${p.id}" data-stream="${id}">Invite</button></div>`).join('')||'<div style="color:var(--live-muted);font-size:11px">No matching guests found.</div>'}
  async function invite(streamId,guestId){const sb=await getClient();if(!sb||!state.user){toast('Sign in to invite guests.');return}const s=state.streams.find(x=>x.id===streamId);const {error}=await sb.from('spike_live_guests').insert({stream_id:streamId,host_id:s?.host_id,guest_id:guestId,note:'Invited from SPIKE Live'});if(error)toast(error.message);else{toast('🎙 Guest invitation sent');close('guestSheet');await event(streamId,'guest_request',{guest_id:guestId});}}
  async function createLive(form){const sb=await getClient();if(!sb||!state.user){toast('Sign in before starting a Live.');return}const fd=new FormData(form);const externalPlayback=String(fd.get('playback_url')||'').trim();if(!externalPlayback&&!state.hostMedia){try{await toggleCamera()}catch(_){}}const row={host_id:state.user.id,title:String(fd.get('title')).trim(),description:String(fd.get('description')||'').trim(),category:String(fd.get('category')),tags:String(fd.get('tags')||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,12),status:'live',playback_url:externalPlayback||null,started_at:new Date().toISOString(),guest_open:fd.get('guest_open')==='true',guest_slots:Number(fd.get('guest_slots')||1)};const {data,error}=await sb.from('spike_live_streams').insert(row).select().single();if(error){toast(error.message);return}close('goLiveSheet');form.reset();await startHostTransport(data.id);toast('🔴 Your SPIKE Live is active');await load();await join(data.id)}
  async function startHostTransport(streamId){if(!window.RTCPeerConnection||!state.hostMedia)return;const sb=await getClient();if(!sb)return;const topic=`spike-live:${streamId}`,ch=sb.channel(topic);state.hostChannel=ch;ch.on('broadcast',{event:'viewer-join'},async({payload})=>{if(payload?.role!=='viewer')return;const peerId=payload.peerId||crypto.randomUUID?.()||String(Date.now()),pc=new RTCPeerConnection(rtcConfig());state.hostPeers.set(peerId,pc);state.hostMedia.getTracks().forEach(t=>pc.addTrack(t,state.hostMedia));pc.onicecandidate=e=>{if(e.candidate)ch.send({type:'broadcast',event:'ice',payload:{role:'host',peerId,candidate:e.candidate,target:peerId}})};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await ch.send({type:'broadcast',event:'offer',payload:{role:'host',peerId,sdp:offer,target:peerId}})}).on('broadcast',{event:'answer'},async({payload})=>{const pc=state.hostPeers.get(payload?.peerId);if(pc?.signalingState==='have-local-offer')try{await pc.setRemoteDescription(payload.sdp)}catch(_){}}).on('broadcast',{event:'ice'},async({payload})=>{const pc=state.hostPeers.get(payload?.peerId);if(pc&&payload?.candidate)try{await pc.addIceCandidate(payload.candidate)}catch(_){}}).on('broadcast',{event:'guest-join'},async({payload})=>{if(payload?.role!=='guest'||!payload.guestId)return;const peerId=payload.peerId||payload.guestId;if(state.hostGuestPeers.has(peerId))return;const pc=new RTCPeerConnection(rtcConfig());state.hostGuestPeers.set(peerId,pc);state.hostMedia.getTracks().forEach(t=>pc.addTrack(t,state.hostMedia));pc.ontrack=e=>{if(e.streams?.[0])guestTile(peerId,payload.name,e.streams[0])};pc.onicecandidate=e=>{if(e.candidate)ch.send({type:'broadcast',event:'guest-ice',payload:{role:'host',peerId,guestId:payload.guestId,candidate:e.candidate,target:peerId}})};pc.onconnectionstatechange=()=>{if(['failed','closed','disconnected'].includes(pc.connectionState)){removeGuestTile(peerId);state.hostGuestPeers.delete(peerId)}};const offer=await pc.createOffer();await pc.setLocalDescription(offer);await ch.send({type:'broadcast',event:'guest-offer',payload:{role:'host',peerId,guestId:payload.guestId,sdp:offer,target:peerId}})}).on('broadcast',{event:'guest-answer'},async({payload})=>{const pc=state.hostGuestPeers.get(payload?.peerId);if(pc?.signalingState==='have-local-offer')try{await pc.setRemoteDescription(payload.sdp)}catch(_){}}).on('broadcast',{event:'guest-ice'},async({payload})=>{const pc=state.hostGuestPeers.get(payload?.peerId);if(pc&&payload?.candidate)try{await pc.addIceCandidate(payload.candidate)}catch(_){}}).on('broadcast',{event:'guest-leave'},({payload})=>{const pc=state.hostGuestPeers.get(payload?.peerId);try{pc?.close()}catch(_){}state.hostGuestPeers.delete(payload?.peerId);removeGuestTile(payload?.peerId)}).subscribe()}
  async function toggleCamera(){if(!navigator.mediaDevices?.getUserMedia){toast('Camera access is not supported here.');return}if(state.hostMedia){state.hostMedia.getTracks().forEach(t=>t.stop());state.hostMedia=null;$('#hostPreview').srcObject=null;$('#cameraState').textContent='Camera preview off';$('#cameraBtn').textContent='Enable camera';return}try{state.hostMedia=await navigator.mediaDevices.getUserMedia({video:{facingMode:'user',width:{ideal:1280},height:{ideal:720}},audio:true});$('#hostPreview').srcObject=state.hostMedia;$('#cameraState').textContent='Camera + microphone ready';$('#cameraBtn').textContent='Disable camera';toast('Camera and microphone ready')}catch(e){toast('Camera permission was denied or unavailable.')}}
  async function loadLivePoll(streamId){const sb=await getClient();if(!sb||!state.user)return;const {data}=await sb.from('spike_live_polls').select('id,question,status,created_at,spike_live_poll_options(id,label,position,vote_count)').eq('stream_id',streamId).eq('status','open').order('created_at',{ascending:false}).limit(1).maybeSingle();state.poll=data||null;renderLivePoll();if(state.poll)subscribePoll(sb,streamId)}
  function renderLivePoll(){const box=$('#livePollPanel');if(!box)return;const p=state.poll;if(!p){box.hidden=true;box.innerHTML='';return}box.hidden=false;const opts=(p.spike_live_poll_options||[]).sort((a,b)=>a.position-b.position);box.innerHTML=`<div class="poll-head"><strong>🗳 ${esc(p.question)}</strong><span>LIVE</span></div><div class="poll-options">${opts.map(o=>`<button class="poll-option" data-poll-vote="${o.id}"><span>${esc(o.label)}</span><b>${Number(o.vote_count)||0}</b></button>`).join('')}</div>`}
  function subscribePoll(sb,streamId){if(state.pollChannel)try{sb.removeChannel(state.pollChannel)}catch(_){}const ch=sb.channel(`spike-live-poll:${streamId}`).on('postgres_changes',{event:'*',schema:'public',table:'spike_live_polls',filter:`stream_id=eq.${streamId}`},()=>loadLivePoll(streamId)).on('postgres_changes',{event:'*',schema:'public',table:'spike_live_poll_options'},p=>{if(state.poll?.id===p.new?.poll_id)loadLivePoll(streamId)}).subscribe();state.pollChannel=ch}
  async function votePoll(optionId){const sb=await getClient();if(!sb||!state.user||!state.poll)return;const option=(state.poll.spike_live_poll_options||[]).find(x=>x.id===optionId);if(!option)return;const {error}=await sb.from('spike_live_poll_votes').insert({poll_id:state.poll.id,option_id:optionId,user_id:state.user.id});if(error){toast(error.code==='23505'?'You already voted.':error.message);return}await sb.from('spike_live_poll_options').update({vote_count:(Number(option.vote_count)||0)+1}).eq('id',optionId);await event(state.watchStreamId,'poll_vote',{poll_id:state.poll.id,option_id:optionId});toast('🗳 Vote counted')}
  async function createPoll(){const sb=await getClient();if(!sb||!state.user||!state.watchStreamId){toast('Host access required.');return}const question=prompt('Poll question');if(!question?.trim())return;const raw=prompt('Options separated by commas','Yes,No');const labels=(raw||'').split(',').map(x=>x.trim()).filter(Boolean).slice(0,5);if(labels.length<2){toast('Add at least two options.');return}const s=state.streams.find(x=>x.id===state.watchStreamId);if(!s||s.host_id!==state.user.id){toast('Only the host can create polls.');return}const {data:p,error}=await sb.from('spike_live_polls').insert({stream_id:state.watchStreamId,host_id:state.user.id,question:question.trim()}).select().single();if(error){toast(error.message);return}const {error:oe}=await sb.from('spike_live_poll_options').insert(labels.map((label,i)=>({poll_id:p.id,label,position:i})));if(oe){toast(oe.message);return}await event(state.watchStreamId,'poll',{poll_id:p.id});await loadLivePoll(state.watchStreamId);toast('🗳 Poll is live')}
  async function loadLiveQuestions(streamId){const sb=await getClient();if(!sb||!state.user)return;const {data,error}=await sb.from('spike_live_questions').select('id,user_id,question,status,created_at').eq('stream_id',streamId).in('status',['pending','answered']).order('created_at',{ascending:false}).limit(40);if(error){console.warn(error);return}state.questions=data||[];renderQuestions();}
  function renderQuestions(){const box=$('#questionQueue');if(!box)return;const pending=state.questions.filter(q=>q.status==='pending');$('#controlQuestionCount').textContent=pending.length;box.innerHTML=pending.length?pending.map(q=>`<div class="question-card"><strong>${esc(q.question)}</strong><small>${esc(q.user_id===state.user?.id?'You':'Viewer')} · ${ago(q.created_at)} ago</small><div class="question-actions"><button data-question-action="answered" data-question-id="${q.id}">Mark answered</button><button data-question-action="dismissed" data-question-id="${q.id}">Dismiss</button></div></div>`).join(''):'<span style="color:var(--live-muted);font-size:9px">No pending questions.</span>'}
  async function submitQuestion(){const q=prompt('Your question');if(!q?.trim()||!state.watchStreamId)return;const sb=await getClient();if(!sb||!state.user){toast('Sign in to ask a question.');return}const {error}=await sb.from('spike_live_questions').insert({stream_id:state.watchStreamId,user_id:state.user.id,question:q.trim().slice(0,500)});if(error){toast(error.message);return}await event(state.watchStreamId,'question',{question:q.trim().slice(0,500)});toast('❓ Question sent')}
  async function updateQuestion(id,status){const sb=await getClient();if(!sb||!state.user)return;const values={status};if(status==='answered')values.answered_at=new Date().toISOString();const {error}=await sb.from('spike_live_questions').update(values).eq('id',id);if(error)toast(error.message);else{await loadLiveQuestions(state.watchStreamId);toast(status==='answered'?'Question marked answered':'Question dismissed')}}
  async function subscribeQuestions(sb,streamId){if(state.questionChannel)try{sb.removeChannel(state.questionChannel)}catch(_){}const ch=sb.channel(`spike-live-questions:${streamId}`).on('postgres_changes',{event:'*',schema:'public',table:'spike_live_questions',filter:`stream_id=eq.${streamId}`},()=>loadLiveQuestions(streamId)).subscribe();state.questionChannel=ch}
  async function subscribePresence(sb,streamId){if(!sb||!state.user)return;if(state.presenceChannel)try{sb.removeChannel(state.presenceChannel)}catch(_){}const ch=sb.channel(`spike-live-presence:${streamId}`,{config:{presence:{key:state.user.id}}});ch.on('presence',{event:'sync'},()=>{state.presenceState=ch.presenceState();renderPresence()}).on('presence',{event:'join'},()=>renderPresence()).on('presence',{event:'leave'},()=>renderPresence());const status=await new Promise(resolve=>ch.subscribe(x=>resolve(x)));if(status==='SUBSCRIBED'){await ch.track({user_id:state.user.id,role:state.watchMode,joined_at:new Date().toISOString()});}state.presenceChannel=ch;renderPresence()}
  function renderPresence(){const stateObj=state.presenceState||{};const rows=Object.entries(stateObj).flatMap(([key,arr])=>Array.isArray(arr)?arr.map(x=>({...x,key})):[]);const unique=[...new Map(rows.map(x=>[x.user_id||x.key,x])).values()];$('#presenceCount').textContent=`${unique.length} watching`;const box=$('#presenceList');if(box)box.innerHTML=unique.slice(0,24).map(x=>`<div class="presence-card"><div class="presence-main"><strong>${esc(x.user_id===state.user?.id?'You':'Participant')}</strong><span class="presence-role">${esc(x.role||'viewer')}</span></div>${state.watchMode==='host'&&x.user_id&&x.user_id!==state.user?.id?`<button class="stream-action" data-moderate="${x.user_id}">Moderate</button>`:''}</div>`).join('')||'<span style="color:var(--live-muted);font-size:9px">No presence yet.</span>'}
  function showModeration(userId){const box=$('#moderationList');if(!box)return;box.innerHTML=`<strong style="font-size:10px">Moderate participant</strong><div class="moderation-actions"><button data-mod-action="warn" data-target="${userId}">Warn</button><button data-mod-action="mute" data-target="${userId}">Mute</button><button data-mod-action="remove" data-target="${userId}">Remove</button><button data-mod-action="block" data-target="${userId}">Block</button></div>`}
  async function moderate(userId,action){const sb=await getClient();if(!sb||!state.user||!state.watchStreamId)return;const reason=prompt('Reason (optional)')||null;const {error}=await sb.from('spike_live_moderation_actions').insert({stream_id:state.watchStreamId,moderator_id:state.user.id,target_user_id:userId,action,reason});if(error){toast(error.message);return}toast(`🛡 ${action} recorded`);}
  async function subscribeLiveEvents(sb,streamId){if(state.eventChannel)try{sb.removeChannel(state.eventChannel)}catch(_){}const ch=sb.channel(`spike-live-events:${streamId}`).on('postgres_changes',{event:'INSERT',schema:'public',table:'spike_live_events',filter:`stream_id=eq.${streamId}`},payload=>{const e=payload.new;if(e.event_type==='spark'){const n=Number($('#sparkLiveCount')?.textContent||0)+1;$('#sparkLiveCount').textContent=n;toast('⚡ Spark!')}if(e.event_type==='moment'){toast('🔥 Live moment marked');const n=Number($('#controlMomentCount')?.textContent||0)+1;$('#controlMomentCount').textContent=n}if(e.event_type==='chat'){const n=Number($('#controlChatRate')?.textContent||0)+1;$('#controlChatRate').textContent=n}if(e.event_type==='poll_vote')loadLivePoll(streamId)}).subscribe();state.eventChannel=ch}
  function cleanupWatch(){const leaving=state.watchStreamId;if(leaving&&state.user){event(leaving,'leave').catch(()=>{});}state.moments=[];renderMoments();try{state.watchPc?.close()}catch(_){}try{state.watchChannel&&getClient().then(sb=>sb?.removeChannel(state.watchChannel))}catch(_){}try{state.chatChannel&&getClient().then(sb=>sb?.removeChannel(state.chatChannel))}catch(_){}try{state.pollChannel&&getClient().then(sb=>sb?.removeChannel(state.pollChannel))}catch(_){}try{state.eventChannel&&getClient().then(sb=>sb?.removeChannel(state.eventChannel))}catch(_){}try{state.questionChannel&&getClient().then(sb=>sb?.removeChannel(state.questionChannel))}catch(_){}try{state.momentChannel&&getClient().then(sb=>sb?.removeChannel(state.momentChannel))}catch(_){}try{state.presenceChannel&&getClient().then(sb=>sb?.removeChannel(state.presenceChannel))}catch(_){}clearInterval(state.presenceTimer);state.presenceTimer=null;state.watchPc=null;state.watchChannel=null;state.chatChannel=null;state.watchStreamId=null;try{state.guestPc?.close()}catch(_){}state.guestPc=null;state.guestChannel=null;if(state.guestMedia){state.guestMedia.getTracks().forEach(t=>t.stop());state.guestMedia=null}$('#watchVideo').srcObject=null;$('#guestStage').innerHTML='';$('#guestStage').hidden=true}
  $('#liveTabs').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(!b)return;state.mode=b.dataset.mode;renderAll();window.scrollTo({top:0,behavior:'smooth'})});
  $('#mainSections').addEventListener('click',e=>{const m=e.target.closest('[data-mode]');if(m){state.mode=m.dataset.mode;renderAll();return}const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action,b.dataset.id)});
  $('#heroSection').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(b)handleAction(b.dataset.action,b.dataset.id)});
  $('#rankBoard').addEventListener('click',e=>{const b=e.target.closest('[data-mode]');if(b){state.mode=b.dataset.mode;renderAll()}});
  document.addEventListener('click',e=>{const inv=e.target.closest('[data-invite]');if(inv)invite(inv.dataset.stream,inv.dataset.invite);const dec=e.target.closest('[data-guest-decision]');if(dec)decideGuest(dec.dataset.guestId,dec.dataset.guestDecision);const c=e.target.closest('[data-close]');if(c)close(c.dataset.close)});
  function handleAction(a,id){if(a==='join')return join(id);if(a==='spark')return event(id,'spark');if(a==='moment')return event(id,'moment');if(a==='save')return save(id);if(a==='guest')return guests(id)}
  $('#searchInput').addEventListener('input',e=>{state.query=e.target.value;renderAll()});
  $('#goLiveBtn')?.addEventListener('click',()=>open('goLiveSheet'));$('#goLiveBtnPrimary')?.addEventListener('click',()=>open('goLiveSheet'));
  const categoryValue=$('#liveCategoryValue'),categoryLabel=$('#liveCategoryLabel'),categoryIcon=$('#liveCategoryIcon'),categoryGrid=$('#categoryGrid'); let pendingCategory=categoryValue?.value||'Chat';
  const updateCategoryTrigger=()=>{const b=categoryGrid?.querySelectorAll('[data-category]');const chosen=[...(b||[])].find(x=>x.dataset.category===pendingCategory);if(categoryLabel)categoryLabel.textContent=pendingCategory;if(categoryIcon)categoryIcon.textContent=chosen?.dataset.icon||'💬'};
  const syncCategoryPicker=()=>{categoryGrid?.querySelectorAll('[data-category]').forEach(b=>{const selected=b.dataset.category===pendingCategory;b.classList.toggle('is-selected',selected);b.setAttribute('aria-selected',String(selected));b.querySelector('i').textContent=selected?'✓':'›';});updateCategoryTrigger()};
  $('#liveCategoryTrigger')?.addEventListener('click',()=>{pendingCategory=categoryValue?.value||'Chat';syncCategoryPicker();open('categoryPickerSheet')});
  categoryGrid?.addEventListener('click',e=>{const b=e.target.closest('[data-category]');if(!b)return;pendingCategory=b.dataset.category;syncCategoryPicker()});
  $('#categoryConfirmBtn')?.addEventListener('click',()=>{const b=[...(categoryGrid?.querySelectorAll('[data-category]')||[])].find(x=>x.dataset.category===pendingCategory);if(categoryValue)categoryValue.value=pendingCategory;if(categoryLabel)categoryLabel.textContent=pendingCategory;if(categoryIcon)categoryIcon.textContent=b?.dataset.icon||'💬';close('categoryPickerSheet')});
  const liveMenu=$('#liveMenu'),liveMenuBtn=$('#liveMenuBtn'),liveMenuClose=$('#liveMenuClose');
  const closeLiveMenu=()=>{if(!liveMenu)return;liveMenu.hidden=true;liveMenu.setAttribute('aria-hidden','true');liveMenuBtn?.setAttribute('aria-expanded','false')};
  const openLiveMenu=()=>{if(!liveMenu)return;liveMenu.hidden=false;liveMenu.setAttribute('aria-hidden','false');liveMenuBtn?.setAttribute('aria-expanded','true')};
  liveMenuBtn?.addEventListener('click',()=>liveMenu?.hidden?openLiveMenu():closeLiveMenu());liveMenuClose?.addEventListener('click',closeLiveMenu);
  liveMenu?.querySelectorAll('[data-live-menu]').forEach(btn=>btn.addEventListener('click',()=>{const action=btn.dataset.liveMenu;closeLiveMenu();if(action==='start')open('goLiveSheet');else if(action==='guests')openGuestInbox();else if(action==='ranking'){renderAllPacks();open('rankingSheet')}else if(action==='feed')location.href='feed.html'}));
  document.addEventListener('click',e=>{if(liveMenu&&!liveMenu.hidden&&!liveMenu.contains(e.target)&&e.target!==liveMenuBtn)closeLiveMenu()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLiveMenu()});$('#rankingBtn').onclick=()=>{renderAllPacks();open('rankingSheet')};$('#guestInboxBtn').onclick=openGuestInbox;$('#rankingBtn').addEventListener('contextmenu',e=>{e.preventDefault();openGuestInbox()});$('#openAllRanks').onclick=()=>{renderAllPacks();open('rankingSheet')};$('#backBtn').onclick=()=>history.length>1?history.back():location.href='index.html';
  function renderAllPacks(){$('#allRankingPacks').innerHTML=packs.map(([id,label,desc])=>`<div><strong>${label}</strong><span>${desc}</span></div>`).join('')}
  $('#sparkBtn').onclick=()=>event(state.watchStreamId,'spark');$('#momentBtn').onclick=markMoment;$('#questionBtn').onclick=submitQuestion;$('#createPollBtn').onclick=createPoll;$('#livePollPanel').addEventListener('click',e=>{const b=e.target.closest('[data-poll-vote]');if(b)votePoll(b.dataset.pollVote)});$('#questionQueue').addEventListener('click',e=>{const b=e.target.closest('[data-question-action]');if(b)updateQuestion(b.dataset.questionId,b.dataset.questionAction)});$('#presenceList').addEventListener('click',e=>{const b=e.target.closest('[data-moderate]');if(b)showModeration(b.dataset.moderate)});$('#moderationList').addEventListener('click',e=>{const b=e.target.closest('[data-mod-action]');if(b)moderate(b.dataset.target,b.dataset.modAction)});  $('#chatForm').addEventListener('submit',e=>{e.preventDefault();sendChat()});$('#goLiveForm').addEventListener('submit',e=>{e.preventDefault();createLive(e.currentTarget)});$('#cameraBtn').onclick=toggleCamera;$('#watchSheet').addEventListener('click',e=>{if(e.target===e.currentTarget){cleanupWatch();close('watchSheet')}});document.addEventListener('click',e=>{if(e.target.closest('[data-close=watchSheet]'))cleanupWatch()});
  $$('.sheet-wrap').forEach(s=>s.addEventListener('click',e=>{if(e.target===s)close(s.id)}));
  load();
  if(new URLSearchParams(location.search).get('start')==='1') setTimeout(()=>open('goLiveSheet'),120);
})();
