/* SPIKE i18n: translation packs live in Supabase, not GitHub. */
(()=>{
'use strict';
const URL='https://cjqpyndceqyqsijihxbb.supabase.co',KEY='sb_publishable_Tqz0TbLLRLwu4XirPTVuiw_sSC9o4Jw',STORE='spike-language';
const client=()=>window.supabaseClient||window.db||window.sb||(window.supabase?.createClient?window.supabase.createClient(URL,KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:false}}):null);
const LANGS={en:'English',fr:'Français',ig:'Igbo',yo:'Yorùbá',ha:'Hausa',pcm:'Nigerian Pidgin'},UI={en:['Language','Choose your language'],fr:['Langue','Choisissez votre langue'],ig:['Asụsụ','Họrọ asụsụ gị'],yo:['Èdè','Yan èdè rẹ'],ha:['Harshe','Zaɓi harshenka'],pcm:['Language','Choose your language']};
let active=LANGS[localStorage.getItem(STORE)]?localStorage.getItem(STORE):'en',pack={},originals=new WeakMap(),observer;
document.documentElement.lang=active;document.documentElement.dataset.spikeLang=active;
const user=el=>!!el?.closest?.('input,textarea,select,option,[contenteditable=true],[data-i18n-ignore],[data-i18n-user-content]');
const ok=n=>{const p=n.parentElement;return !!p&&!user(p)&&!['SCRIPT','STYLE','NOSCRIPT','TEMPLATE','PRE','CODE'].includes(p.tagName)&&/[A-Za-zÀ-ÿ]/.test(n.nodeValue||'')};
const norm=t=>t.replace(/\s+/g,' ').trim();
function restore(){const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode())if(originals.has(n))n.nodeValue=originals.get(n);document.querySelectorAll('[data-spike-i18n-attrs]').forEach(e=>{try{for(const[a,v]of Object.entries(JSON.parse(e.getAttribute('data-spike-i18n-attrs'))))e.setAttribute(a,v)}catch{}e.removeAttribute('data-spike-i18n-attrs')})}
function apply(){if(active==='en'){restore();return}const w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);let n;while(n=w.nextNode()){if(!ok(n))continue;if(!originals.has(n))originals.set(n,n.nodeValue);const o=originals.get(n),t=pack[norm(o)];if(t&&t!==norm(o)){const a=o.match(/^\s*/)?.[0]||'',b=o.match(/\s*$/)?.[0]||'';n.nodeValue=a+t+b}}document.querySelectorAll('[placeholder],[title],[aria-label],[alt]').forEach(e=>{if(user(e))return;const old={};for(const a of ['placeholder','title','aria-label','alt']){const v=e.getAttribute(a),t=v&&pack[v];if(v&&t&&t!==v){old[a]=v;e.setAttribute(a,t)}}if(Object.keys(old).length)e.setAttribute('data-spike-i18n-attrs',JSON.stringify(old))});document.documentElement.lang=active}
async function savePreference(lang){try{if(window.supabase?.createClient){const db=client();if(!db)return;const {data:{session}}=await db.auth.getSession();if(session?.user){await db.from('user_app_settings').upsert({user_id:session.user.id,language_code:lang,updated_at:new Date().toISOString()},{onConflict:'user_id'})}}}catch(e){console.warn('[SPIKE i18n preference]',e)}}
async function load(lang){if(lang==='en')return {};try{const r=await fetch(URL+'/rest/v1/spike_i18n_packs?select=translations&language_code=eq.'+encodeURIComponent(lang),{headers:{apikey:KEY,Authorization:'Bearer '+KEY,Accept:'application/json'},cache:'no-store'});if(r.ok){const rows=await r.json();if(rows[0]?.translations)return rows[0].translations}}catch(e){}const local=await fetch('assets/i18n/'+encodeURIComponent(lang)+'.json',{cache:'force-cache'});if(!local.ok)throw Error('Translation pack unavailable');return await local.json()}
function selector(){if(!location.pathname.endsWith('settings.html')||document.getElementById('spike-language-setting'))return;const s=document.createElement('section');s.id='spike-language-setting';s.className='card';s.setAttribute('data-i18n-ignore','');s.innerHTML='<div class="section">Language</div><div class="row"><div><strong id="spike-language-label">Language</strong><small id="spike-language-hint">Choose your language</small></div><select id="spike-language-select" class="control" aria-label="Language"><option value="en">English</option><option value="fr">Français</option><option value="ig">Igbo</option><option value="yo">Yorùbá</option><option value="ha">Hausa</option><option value="pcm">Nigerian Pidgin</option></select></div>';const m=document.querySelector('main');m?.insertBefore(s,m.firstChild);const q=s.querySelector('select');q.value=active;q.onchange=async()=>{active=q.value;localStorage.setItem(STORE,active);await savePreference(active);location.reload()}}
async function boot(){try{if(window.supabase?.createClient){const db=client();if(!db)return;const {data:{session}}=await db.auth.getSession();if(session?.user){const r=await db.from('user_app_settings').select('language_code').eq('user_id',session.user.id).maybeSingle();if(r.data?.language_code&&LANGS[r.data.language_code]){active=r.data.language_code;localStorage.setItem(STORE,active)}}}}catch(e){console.warn('[SPIKE i18n preference load]',e)}try{pack=await load(active)}catch(e){console.warn('[SPIKE i18n]',e);active='en';localStorage.setItem(STORE,'en');pack={}}apply();selector();const q=document.getElementById('spike-language-select');if(q){q.value=active;const u=UI[active];document.getElementById('spike-language-label').textContent=u[0];document.getElementById('spike-language-hint').textContent=u[1]}document.documentElement.dataset.spikeI18nReady='1';observer=new MutationObserver(ms=>{if(ms.some(m=>m.addedNodes.length))apply()});observer.observe(document.body,{subtree:true,childList:true})}
document.addEventListener('DOMContentLoaded',boot,{once:true});window.SPIKE_I18N={languages:LANGS,get language(){return active},setLanguage:l=>{if(!LANGS[l])return false;active=l;localStorage.setItem(STORE,l);location.reload();return true}};
})();
