-- Live admin control center hardening: Auth-wide directory, wallet grants,
-- user role/activation controls, announcement lifecycle, and audit access.
-- This migration was applied to the SPIKE Supabase project.

create or replace function public.admin_list_users_v2(
  p_search text default '', p_limit integer default 100, p_offset integer default 0, p_filter text default 'all'
) returns table(user_id uuid,email text,display_name text,username text,sp_id text,coins bigint,created_at timestamptz,room_count bigint,is_admin boolean,status text,banned_until timestamptz,banned_at timestamptz,banned_by uuid,ban_reason text,last_seen_at timestamptz,providers text[],verified boolean,activated boolean)
language sql stable security definer set search_path='public','auth' as $$
select u.id,u.email,coalesce(p.display_name,u.raw_user_meta_data->>'display_name',u.raw_user_meta_data->>'full_name'),p.username,p.sp_id,coalesce(w.balance,0)::bigint,coalesce(p.created_at,u.created_at),(select count(*) from public.room_members rm where rm.user_id=u.id),coalesce(p.role in ('admin','super_admin'),false),case when u.deleted_at is not null then 'deleted' when p.id is null then 'profile_missing' when p.restricted_at is not null and (p.restricted_until is null or p.restricted_until>now()) then 'banned' when p.activated=false then 'inactive' else 'active' end,p.restricted_until,p.restricted_at,p.restricted_by,p.restriction_reason,(select up.last_seen from public.user_presence up where up.user_id=u.id),coalesce((select array_agg(distinct i.provider order by i.provider) from auth.identities i where i.user_id=u.id),'{}'::text[]),coalesce(p.verified,false),coalesce(p.activated,true)
from auth.users u left join public.profiles p on p.id=u.id left join public.wallets w on w.user_id=u.id
where public.admin_guard() and u.deleted_at is null and (coalesce(trim(p_search),'')='' or coalesce(p.display_name,'') ilike '%'||trim(p_search)||'%' or coalesce(p.username,'') ilike '%'||ltrim(trim(p_search),'@')||'%' or coalesce(p.sp_id,'') ilike '%'||trim(p_search)||'%' or coalesce(u.email,'') ilike '%'||trim(p_search)||'%' or u.id::text ilike '%'||trim(p_search)||'%' or exists(select 1 from auth.identities si where si.user_id=u.id and si.provider ilike '%'||trim(p_search)||'%'))
and (coalesce(lower(p_filter),'all')='all' or (lower(p_filter)='active' and p.activated=true and not (p.restricted_at is not null and (p.restricted_until is null or p.restricted_until>now()))) or (lower(p_filter)='banned' and p.restricted_at is not null and (p.restricted_until is null or p.restricted_until>now())) or (lower(p_filter)='verified' and p.verified=true) or (lower(p_filter)='unverified' and coalesce(p.verified,false)=false) or (lower(p_filter)='admin' and p.role in ('admin','super_admin')) or (lower(p_filter)='profile_missing' and p.id is null))
order by coalesce(p.created_at,u.created_at) desc limit greatest(1,least(coalesce(p_limit,100),500)) offset greatest(0,coalesce(p_offset,0));$$;
revoke all on function public.admin_list_users_v2(text,integer,integer,text) from public,anon; grant execute on function public.admin_list_users_v2(text,integer,integer,text) to authenticated;

create or replace function public.admin_grant_coins(p_user_id uuid,p_amount bigint,p_reason text) returns jsonb language plpgsql security definer set search_path='pg_catalog','public','auth' as $$
declare actor uuid:=auth.uid(); actor_role text; v_wallet public.wallets; v_before bigint; v_after bigint; v_ref uuid:=gen_random_uuid(); v_reason text:=nullif(left(trim(coalesce(p_reason,'')),500),'');
begin select role into actor_role from public.profiles where id=actor; if actor_role not in ('admin','super_admin') then raise exception 'Admin access required' using errcode='42501'; end if; if p_user_id is null then raise exception 'User is required'; end if; if p_amount is null or p_amount<1 or p_amount>1000000 then raise exception 'Coin amount must be between 1 and 1,000,000'; end if; if v_reason is null then raise exception 'A reason is required'; end if; if not exists(select 1 from auth.users where id=p_user_id and deleted_at is null) then raise exception 'User not found'; end if; select * into v_wallet from public.wallets where user_id=p_user_id for update; if not found then insert into public.wallets(user_id,balance) values(p_user_id,0) returning * into v_wallet; end if; v_before:=coalesce(v_wallet.balance,0); v_after:=v_before+p_amount; update public.wallets set balance=v_after,updated_at=now() where user_id=p_user_id; insert into public.coin_ledger(user_id,amount,balance_before,balance_after,transaction_type,reference_id,reason) values(p_user_id,p_amount,v_before,v_after,'admin_grant',v_ref::text,v_reason); insert into public.admin_audit(actor_id,action,target_user_id,role,details) values(actor,'coins_granted',p_user_id,actor_role,jsonb_build_object('amount',p_amount,'balance_before',v_before,'balance_after',v_after,'reason',v_reason,'reference_id',v_ref)); return jsonb_build_object('ok',true,'user_id',p_user_id,'amount',p_amount,'balance_before',v_before,'balance_after',v_after,'reference_id',v_ref,'reason',v_reason); end $$;
revoke all on function public.admin_grant_coins(uuid,bigint,text) from public,anon; grant execute on function public.admin_grant_coins(uuid,bigint,text) to authenticated;

create or replace function public.admin_set_user_activation(p_user_id uuid,p_activated boolean,p_reason text default null) returns jsonb language plpgsql security definer set search_path='pg_catalog','public','auth' as $$ begin if p_activated then return public.admin_unrestrict_user(p_user_id); end if; return public.admin_ban_user(p_user_id,0,p_reason); end $$;
revoke all on function public.admin_set_user_activation(uuid,boolean,text) from public,anon; grant execute on function public.admin_set_user_activation(uuid,boolean,text) to authenticated;

create or replace function public.admin_set_user_role(p_user_id uuid,p_role text,p_reason text default null) returns jsonb language plpgsql security definer set search_path='public','pg_catalog','auth' as $$
declare r public.profiles; old_role text; actor_role text; begin select role into actor_role from public.profiles where id=auth.uid(); if actor_role not in ('admin','super_admin') then raise exception 'Admin access required'; end if; if p_role not in ('user','support_admin','content_admin','moderation_admin','admin','super_admin') then raise exception 'Invalid role'; end if; select role into old_role from public.profiles where id=p_user_id for update; if old_role is null then raise exception 'User not found'; end if; if actor_role<>'super_admin' and (old_role in ('admin','super_admin') or p_role in ('admin','super_admin')) then raise exception 'Only a super admin can change administrator roles'; end if; update public.profiles set role=p_role,updated_at=now() where id=p_user_id returning * into r; insert into public.admin_audit(actor_id,action,target_user_id,role,details) values(auth.uid(),'user_role_changed',p_user_id,actor_role,jsonb_build_object('previous_role',old_role,'new_role',p_role,'reason',nullif(left(trim(coalesce(p_reason,'')),500),''))); return jsonb_build_object('ok',true,'user_id',p_user_id,'previous_role',old_role,'role',p_role); end $$;
revoke all on function public.admin_set_user_role(uuid,text,text) from public,anon; grant execute on function public.admin_set_user_role(uuid,text,text) to authenticated;

create or replace function public.admin_announcement_list(p_status text default null,p_limit integer default 100) returns setof public.announcement_campaigns language plpgsql stable security definer set search_path='public','pg_catalog' as $$ begin if not public.admin_guard() then raise exception 'Admin access required'; end if; update public.announcement_campaigns set status='expired',active=false,updated_at=now() where ends_at is not null and ends_at<=now() and status not in ('completed','cancelled','expired'); return query select a.* from public.announcement_campaigns a where p_status is null or p_status='all' or a.status=p_status order by a.created_at desc limit greatest(1,least(coalesce(p_limit,100),500)); end $$;
revoke all on function public.admin_announcement_list(text,integer) from public,anon; grant execute on function public.admin_announcement_list(text,integer) to authenticated;

create or replace function public.admin_announcement_create(p_title text,p_body text,p_audience text,p_publish_at timestamptz,p_expires_at timestamptz,p_severity text) returns uuid language plpgsql security definer set search_path='public','auth','pg_catalog' as $$ declare cid uuid; begin if p_expires_at is not null and p_expires_at<=p_publish_at then raise exception 'Expiration must be after publish time'; end if; cid:=public.admin_create_announcement_campaign(p_title,p_body,p_severity,case when p_audience in ('all','active') then p_audience else 'all' end,null,p_publish_at,p_expires_at,true); insert into public.admin_audit(actor_id,action,role,details) values(auth.uid(),'announcement_created',(select role from public.profiles where id=auth.uid()),jsonb_build_object('campaign_id',cid)); return cid; end $$;
revoke all on function public.admin_announcement_create(text,text,text,timestamptz,timestamptz,text) from public,anon; grant execute on function public.admin_announcement_create(text,text,text,timestamptz,timestamptz,text) to authenticated;

create or replace function public.admin_announcement_update(p_id uuid,p_title text,p_body text,p_audience text,p_publish_at timestamptz,p_expires_at timestamptz,p_severity text,p_reason text) returns public.announcement_campaigns language plpgsql security definer set search_path='public','auth','pg_catalog' as $$ declare r public.announcement_campaigns; delivered integer; begin if not public.admin_guard() then raise exception 'Admin access required'; end if; if p_expires_at is not null and p_expires_at<=p_publish_at then raise exception 'Expiration must be after publish time'; end if; select * into r from public.announcement_campaigns where id=p_id for update; if not found then raise exception 'Announcement not found'; end if; if r.status in ('completed','cancelled','expired') then raise exception 'This announcement can no longer be edited'; end if; select count(*) into delivered from public.announcement_recipients where campaign_id=p_id and delivered_at is not null; if delivered>0 then raise exception 'An announcement with delivered notifications cannot be edited'; end if; update public.announcement_campaigns set title=trim(p_title),body=trim(p_body),audience=case when p_audience in ('all','active') then p_audience else 'all' end,publish_at=p_publish_at,ends_at=p_expires_at,severity=p_severity,status=case when p_publish_at>now() then 'scheduled' else 'processing' end,active=true,updated_at=now() where id=p_id returning * into r; insert into public.admin_audit(actor_id,action,role,details) values(auth.uid(),'announcement_updated',(select role from public.profiles where id=auth.uid()),jsonb_build_object('campaign_id',p_id,'reason',nullif(left(trim(coalesce(p_reason,'')),500),''))); return r; end $$;
revoke all on function public.admin_announcement_update(uuid,text,text,text,timestamptz,timestamptz,text,text) from public,anon; grant execute on function public.admin_announcement_update(uuid,text,text,text,timestamptz,timestamptz,text,text) to authenticated;

create or replace function public.admin_announcement_cancel(p_id uuid,p_reason text default null) returns boolean language plpgsql security definer set search_path='public','auth','pg_catalog' as $$ declare r public.announcement_campaigns; begin if not public.admin_guard() then raise exception 'Admin access required'; end if; select * into r from public.announcement_campaigns where id=p_id for update; if not found then raise exception 'Announcement not found'; end if; if r.status in ('completed','cancelled','expired') then return false; end if; update public.announcement_campaigns set active=false,status='cancelled',updated_at=now() where id=p_id; insert into public.admin_audit(actor_id,action,role,details) values(auth.uid(),'announcement_cancelled',(select role from public.profiles where id=auth.uid()),jsonb_build_object('campaign_id',p_id,'reason',nullif(left(trim(coalesce(p_reason,'')),500),''))); return true; end $$;
revoke all on function public.admin_announcement_cancel(uuid,text) from public,anon; grant execute on function public.admin_announcement_cancel(uuid,text) to authenticated;

create or replace function public.admin_process_scheduled_announcements(p_batch_size integer default 250) returns integer language plpgsql security definer set search_path='public','pg_catalog' as $$ declare total integer:=0; n integer; r record; begin if not public.admin_guard() then raise exception 'Admin access required'; end if; update public.announcement_campaigns set status='expired',active=false,updated_at=now() where ends_at is not null and ends_at<=now() and status not in ('completed','cancelled','expired'); for r in select id from public.announcement_campaigns where active=true and publish_at<=now() and (ends_at is null or ends_at>now()) and status in ('scheduled','processing') order by publish_at asc limit 50 loop n:=public.admin_process_announcement(r.id,greatest(1,least(coalesce(p_batch_size,250),500))); total:=total+n; end loop; return total; end $$;
revoke all on function public.admin_process_scheduled_announcements(integer) from public,anon; grant execute on function public.admin_process_scheduled_announcements(integer) to authenticated;

create or replace function public.admin_audit_list(p_limit integer default 100) returns setof public.admin_audit language sql stable security definer set search_path='public' as $$ select * from public.admin_audit where admin_guard() order by created_at desc limit greatest(1,least(coalesce(p_limit,100),500)); $$;
revoke all on function public.admin_audit_list(integer) from public,anon; grant execute on function public.admin_audit_list(integer) to authenticated;
