-- SPIKE Live Audience Engine: polls + realtime participation
create table if not exists public.spike_live_polls (id uuid primary key default gen_random_uuid(), stream_id uuid not null references public.spike_live_streams(id) on delete cascade, host_id uuid not null, question text not null check(char_length(question) between 3 and 240), status text not null default 'open' check(status in ('open','closed')), created_at timestamptz not null default now(), closed_at timestamptz);
create table if not exists public.spike_live_poll_options (id uuid primary key default gen_random_uuid(), poll_id uuid not null references public.spike_live_polls(id) on delete cascade, label text not null check(char_length(label) between 1 and 100), position int not null default 0, vote_count int not null default 0);
create table if not exists public.spike_live_poll_votes (poll_id uuid not null references public.spike_live_polls(id) on delete cascade, option_id uuid not null references public.spike_live_poll_options(id) on delete cascade, user_id uuid not null, created_at timestamptz not null default now(), primary key(poll_id,user_id));
alter table public.spike_live_polls enable row level security; alter table public.spike_live_poll_options enable row level security; alter table public.spike_live_poll_votes enable row level security;
grant select,insert,update on public.spike_live_polls to authenticated; grant select,insert,update on public.spike_live_poll_options to authenticated; grant select,insert on public.spike_live_poll_votes to authenticated;
create index if not exists idx_live_polls_stream_status on public.spike_live_polls(stream_id,status,created_at desc); create index if not exists idx_live_poll_options_poll on public.spike_live_poll_options(poll_id,position);
drop policy if exists "polls select" on public.spike_live_polls; create policy "polls select" on public.spike_live_polls for select to authenticated using (exists(select 1 from public.spike_live_streams s where s.id=stream_id and s.status='live'));
drop policy if exists "polls host insert" on public.spike_live_polls; create policy "polls host insert" on public.spike_live_polls for insert to authenticated with check(host_id=(select auth.uid()) and exists(select 1 from public.spike_live_streams s where s.id=stream_id and s.host_id=(select auth.uid()) and s.status='live'));
drop policy if exists "polls host update" on public.spike_live_polls; create policy "polls host update" on public.spike_live_polls for update to authenticated using(host_id=(select auth.uid())) with check(host_id=(select auth.uid()));
drop policy if exists "poll options select" on public.spike_live_poll_options; create policy "poll options select" on public.spike_live_poll_options for select to authenticated using(exists(select 1 from public.spike_live_polls p join public.spike_live_streams s on s.id=p.stream_id where p.id=poll_id and s.status='live'));
drop policy if exists "poll options insert" on public.spike_live_poll_options; create policy "poll options insert" on public.spike_live_poll_options for insert to authenticated with check(exists(select 1 from public.spike_live_polls p where p.id=poll_id and p.host_id=(select auth.uid())));
drop policy if exists "poll options update" on public.spike_live_poll_options; create policy "poll options update" on public.spike_live_poll_options for update to authenticated using(exists(select 1 from public.spike_live_polls p where p.id=poll_id and p.host_id=(select auth.uid()))) with check(exists(select 1 from public.spike_live_polls p where p.id=poll_id and p.host_id=(select auth.uid())));
drop policy if exists "poll votes select" on public.spike_live_poll_votes; create policy "poll votes select" on public.spike_live_poll_votes for select to authenticated using(user_id=(select auth.uid()));
drop policy if exists "poll votes insert" on public.spike_live_poll_votes; create policy "poll votes insert" on public.spike_live_poll_votes for insert to authenticated with check(user_id=(select auth.uid()) and exists(select 1 from public.spike_live_polls p join public.spike_live_streams s on s.id=p.stream_id where p.id=poll_id and p.status='open' and s.status='live') and exists(select 1 from public.spike_live_poll_options o where o.id=option_id and o.poll_id=poll_id));
alter publication supabase_realtime add table public.spike_live_polls; alter publication supabase_realtime add table public.spike_live_poll_options;
